name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Qt using official installer
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.2'
        arch: 'win64_msvc2019_64'
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{env.QTDIR}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Debug - List build directory
      run: |
        echo "Build directory contents:"
        dir ${{github.workspace}}\build\Release\
    
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Wordle_Calculator_Windows
        path: ${{github.workspace}}/build/Release/
        if-no-files-found: ignore

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt using Homebrew
      run: |
        brew install qt@6
        echo "QTDIR=/opt/homebrew/opt/qt@6" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@6" >> $GITHUB_ENV
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{env.CMAKE_PREFIX_PATH}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Debug - List build directory
      run: |
        echo "Build directory contents:"
        ls -la ${{github.workspace}}/build/
        echo "Looking for app bundle..."
        find ${{github.workspace}}/build/ -name "*.app" -type d
    
    - name: Deploy Qt (if app exists)
      run: |
        if [ -d "${{github.workspace}}/build/Wordle_Calculator.app" ]; then
          echo "Deploying Qt libraries..."
          ${{env.QTDIR}}/bin/macdeployqt ${{github.workspace}}/build/Wordle_Calculator.app
          echo "Qt deployment completed successfully"
          echo "App bundle size:"
          du -sh ${{github.workspace}}/build/Wordle_Calculator.app
        else
          echo "App bundle not found, skipping Qt deployment"
          exit 0
        fi
    
    - name: Zip app bundle
      run: |
        cd ${{github.workspace}}/build
        zip -r Wordle_Calculator_macOS.zip Wordle_Calculator.app
    
    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Wordle_Calculator_macOS
        path: ${{github.workspace}}/build/Wordle_Calculator_macOS.zip
        if-no-files-found: ignore 